version: '2'

services:
  chatapp: &app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - "APP_CONSUMER_KEY=4401369695-ouuhm5dn5l9le9qekvs02gisslhecqft.apps.googleusercontent.com"
      - "APP_CONSUMER_SECRET=KJhRnMjUdAgsrsVmA7eqljMw"
      - "APP_SECRET_KEY=keyboard kittens"
      - "APP_AMQP_URL=amqp://rabbit"
      - "FLASK_DEBUG=1"
      - "FLASK_APP=app.py"
    command: bash -c "sleep 5 && ./app.py"

  # Normally you wouldn't do this, but since we are running on the same
  # host you otherwise get port conflicts
  chatapp_two:
    <<: *app
    ports:
      - "5001:5000"

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
